add_dropdown_menu
Mike47ip/mobilePortfolioWeb pull request #10
Opened 2023-06-21 10:46 UTC by Mike47ip

add_dropdown_menu to he mobile version of the portfolio

2023-06-21 12:15 UTC, ishimwezachee requested changes
Hi @Mike47ip  and @paulshaun-kdtk, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
✅ Well organized project 
✅ Github flow is well implemented 
✅ project is working as expected 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 12:15 UTC, ishimwezachee commented on style.css
> +} */
- [ ]  You should not commit inline comments. They will make your project look messy.  remove all commented codes in your project to have clear and clean source codes.

2023-06-21 13:51 UTC, Mike47ip commented
Dear reviewer kindly ignore the webhint error. There seem to be a bugging issue with the linters. Technical support advice that we ignore.

![ERR REQUIRE ESM](https://github.com/Mike47ip/mobilePortfolioWeb/assets/122385966/a9a26413-86fa-4a4a-b3cd-8396f291af5d)

2023-06-21 13:54 UTC, ShadyShawkat approved these changes
## Hi @Mike47ip, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-21 14:13 UTC, merged

2023-06-30 18:15 UTC, Mike47ip commented
@ShadyShawkat bro I cannot go on to submit the project as completed after you approved it. There seem to be something wrong. Please advice what i do now