Add popup window
Mike47ip/mobilePortfolioWeb pull request #11
Opened 2023-06-23 19:16 UTC by Mike47ip

Merge Popup Window to  Main

2023-06-23 23:47 UTC, Efiamotu-1 requested changes
Hi @Mike47ip , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 23:47 UTC, Efiamotu-1 commented on index.html
- [ ] your popup on mobile device is currently not consistent with the provided figma template, there is no image and the alignment is not consistent. please i kindly suggest you design your mobile popup tomatch the figma template :+1: :sparkles: 
- figma design
![inc](https://github.com/Mike47ip/mobilePortfolioWeb/assets/89055502/84e0205d-5cd3-48d6-a12d-8381d57c993e)
- your design
![incc](https://github.com/Mike47ip/mobilePortfolioWeb/assets/89055502/e1c80089-9e29-42a7-adc0-76cbbd1ccd43)

2023-06-23 23:47 UTC, Efiamotu-1 commented on index.html
- [ ] Your popup for mobile screens doesn't match correctly the provided figma template below, you do not have the appropriate image displayed for each popup and the close button is also not the same. please kindly adapt your popup design to match the provided figma template
- [ ] Also the placement of the `see live & see source` button is not correct as shown on figma please adjust your design correctly. :+1: :sparkles: 
- figma design
![but](https://github.com/Mike47ip/mobilePortfolioWeb/assets/89055502/56ce1a02-8671-4378-9fb7-5fc8cc2eed7e)
- your design
![buto](https://github.com/Mike47ip/mobilePortfolioWeb/assets/89055502/9f525e26-0854-4a7f-9365-b186175956cf)

2023-06-24 13:08 UTC, Mike47ip commented
**### Please ignore Webhint Error. Technical Support say it is a general bug.**

![ERR REQUIRE ESM](https://github.com/Mike47ip/mobilePortfolioWeb/assets/122385966/f0b169f3-2bdd-4b70-9958-14c88930df5f)

2023-06-24 13:28 UTC, usorfaitheloho requested changes
Hi @Mike47ip  :thumbsup:  ,

This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are still some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

## Highlights
- Good job on implementing the design of the previous reviewer ✔️ 
-  Well-structured files ✔️
<br/>
<br/>
<br/>

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 13:28 UTC, usorfaitheloho commented on index.html
You did well in making the changes suggestedd  by the previous reviewer, please kindly fix the alignment issue in your  buttons for the mobile-popup, as it is always necessary that your design meets the figma template requirement 😄 

Figma template :
![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/20537712/bb4e1c1b-b9f1-486e-8734-57b38f28dcef)

Your design :
![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/20537712/5045b4fe-0a7c-4ff2-8f18-cafe0db2a162)

2023-06-24 13:28 UTC, usorfaitheloho commented on index.html
As suggested by the previous reviewer, kindly fix the alignment of the buttons as they seem to be away from the right positions and also the buttons should be aligned properly and it has a dark background. please implement these changes so your design looks better 😄 

Your design :
![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/20537712/fc889e81-4f81-4d60-9bf8-de9c7e4759d2)

![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/20537712/e19886c3-1622-49f8-a964-a1f5db9adeeb)

Figma design :
![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/20537712/943dd597-4c64-4df7-bbc4-5b4b1b76f3fb)

2023-06-24 13:57 UTC, rloterh reviewed
Hi Michael,
 
 While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
 
 ## Invalid Code Review Request
You have submitted this project under the wrong activity name. Kindly ensure to submit this project under the right activity.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-24 14:27 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Mike47ip 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 14:27 UTC, anagudelogu commented on index.html
- [ ] As requested by the previous reviewer, please consider aligning the buttons correctly. Please consider fixing it! 🤓 🔧  Currently, this is how they look like:

|Template|Your design|
|---|---|
| ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/77069011/d7fa7cb9-e4bb-4981-a9e4-7356a4450561) | ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/77069011/667967d7-1460-4100-9675-2771af416015) |


- [ ] Also, the close button is supposed to overlay the image. Please consider fixing this! 🤓 🔧 

|Template|Your design|
|---|---|
| ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/77069011/d7fa7cb9-e4bb-4981-a9e4-7356a4450561) | ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/77069011/2c1aee4e-c5a4-4e0a-a250-c6d13f983545) |

2023-06-30 17:40 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @Mike47ip 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please take note that since you're repeating the week with unapproved PR and this is a pair-programming activity you'll have to create a new PR with the commits of your newly assigned coding partner, according to Microverse's policy.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-30 18:41 UTC, Ofarouq310 reviewed
Hi @Mike47ip, ✋ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🔴 Invalid Code Review Request

- If you received a message from Student Success about your partner's situation, kindly add a screenshot in the Pull request summary so we can proceed to review your request. Otherwise, if the one informed you is your partner, you need to contact the student success and they will help you.

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-30 21:08 UTC, Mike47ip commented
![Screenshot (129)](https://github.com/Mike47ip/mobilePortfolioWeb/assets/122385966/40eeecbe-0f61-4125-b7b4-785ef5d8f389)


Please Note that I received a message from Student's success informing me about my partner dropping off. 
Please go on to approve this PR because I have no partner now to commit on my repo. Thank you!

2023-06-30 21:31 UTC, Ofarouq310 requested changes
Hi @Mike47ip, ✋  

Good job so far! 💪 
There are some issues that you still need to work on to go to the next project but you are almost there! 🥈 

![giphy](https://github.com/Mike47ip/mobilePortfolioWeb/assets/102612396/3f056485-2225-4ea2-9f45-d3328c7451d9)

## Highlights
✅ Descriptive PR title & summary.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 21:31 UTC, Ofarouq310 commented on index.js
> +});
- [ ] For better clean code, kindly delete any commented code.

2023-06-30 21:31 UTC, Ofarouq310 commented on index.js
> +    });
- [ ] KIndly make sure to style the buttons as much as close to the design, spacings, margins, paddings, and icons, kindly address this issue.

Mobile view

| Your design | Actual design |
| ------------- | ------------- |
| ![Screenshot 2023-07-01 002159](https://github.com/Mike47ip/mobilePortfolioWeb/assets/102612396/d20f9758-845f-4280-bcf7-5d5fafb74bcf)  | ![Screenshot 2023-07-01 002210](https://github.com/Mike47ip/mobilePortfolioWeb/assets/102612396/eff044be-abc5-4d0b-b402-3db4fc8ea5d7) |

Desktop 

| Your design | Actual design |
| ------------- | ------------- |
| ![Screenshot 2023-07-01 002236](https://github.com/Mike47ip/mobilePortfolioWeb/assets/102612396/99c7443c-555b-4c69-883c-77b3aa2595fb) | ![Screenshot 2023-07-01 002243](https://github.com/Mike47ip/mobilePortfolioWeb/assets/102612396/90e07758-97fa-4e5a-af91-1b2bce442812) |

2023-06-30 23:38 UTC, Mike47ip commented
Just work has been reviewed long enough. Can you kindly approve it so it so we can all go to sleep?

2023-07-01 01:20 UTC, shahadat3669 approved these changes
Hi @Mike47ip , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅ Good PR Description
✅ Good PR title
✅ Good use of GitHub Flows
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 16:21 UTC, cloud007bond commented
- This is an excellent project no error
- No error

2023-07-07 09:06 UTC, merged