Final
Mike47ip/mobilePortfolioWeb pull request #2
Opened 2023-06-03 20:41 UTC by Mike47ip

All remaining key elements of the body and footer section of the Portfolio page was been implemented and designed to finalized the entire project. This capstone is my first project completion in this Microverse cohort. This website has links into my social media accounts.

2023-06-03 21:03 UTC, stanleySimeon requested changes
# Hi @Mike47ip, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive Pull Request (PR). The PR descriptions should contain a summary of the changes you have in the project/PR. This gives the reviewer an idea of the changes that took place in this particular PR. Kindly fix this before requesting another review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 21:27 UTC, Ofarouq310 reviewed
Hi @Mike47ip,✋ 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🔴  Invalid Code Review Request

![giphy](https://github.com/sadat-Ramin/My-Portfolio/assets/102612396/e86d7266-0567-43bf-9c66-e796b7f7c5d2)

- You have submitted a project, that does not have a descriptive pull request title,  your Pull request title should be short, and concise, and addresses what you are implementing, in your case, it could be, `Finish mobile version` or something similar, simpler. Please refer to the next picture to help you how to edit the title.
![image](https://github.com/Fentahunn/portfolio_one/assets/102612396/acfbea30-fa50-4379-91f9-0bb9d45bd16d)

- Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 22:05 UTC, shahadat3669 requested changes
Hi @Mike47ip >, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media1.giphy.com/media/jmqAUNFXAElgafPK0g/giphy.gif"/>

## Invalid Code Review Request

You have submitted a project, that is invalid because : 
- The branch name you have chosen does not provide a clear indication of the feature or action being implemented. It is important to use descriptive branch names that accurately describe the purpose of the branch. For example, instead of a generic name like "feature1," consider using names like "**created\_sidebar**" or "**added\_comments\_section**" that convey the specific feature or action being worked on. :pray: Please rename the branch to a meaningful name. Check out this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further help. :+1:
- You have an invalid readme file. Please update your readme file as the readme template.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 22:24 UTC, Mike47ip commented
Come on man. I am running out of time here.

On Sat, 3 Jun 2023 at 22:05, Shahadat Hossain ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi <STUDENT_MENTION>,
>
> While you made a great effort in this project, unfortunately, I cannot
> proceed to review your code.
>
>
> <https://camo.githubusercontent.com/2dd4488ba08c09a3570b7ffd2c7ec7bb24478d61f7f5f5b91e65395bdc0af04b/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f6a6d7141554e465841456c676166504b30672f67697068792e676966>
> Invalid Code Review Request
>
> You have submitted a project, that is invalid because :
>
>    - The branch name you have chosen does not provide a clear indication
>    of the feature or action being implemented. It is important to use
>    descriptive branch names that accurately describe the purpose of the
>    branch. For example, instead of a generic name like "feature1," consider
>    using names like "*created_sidebar*" or "*added_comments_section*"
>    that convey the specific feature or action being worked on. 🙏 Please
>    rename the branch to a meaningful name. Check out this official
>    document
>    <https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch>
>    for further help. 👍
>    - You have an invalid readme file. Please update your readme file as
>    the readme template.
>
> Your Code Review Request will be marked as invalid in your Dashboard, so
> please submit a new one once you are ready 🙏
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *Invalid Code Review Request does not count into the code reviews limit.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Mike47ip/mobilePortfolioWeb/pull/2#pullrequestreview-1460277020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5FXMLVBCYKPMDCEU3TGZBTXJOYJVANCNFSM6AAAAAAYZPY6PE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-03 22:49 UTC, shahadat3669 requested changes
Hi  @Mike47ip , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
 <img src="https://media1.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights

✅ Descriptive PR title and summary.
✅ No linters errors.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [Optional] The branch name you have chosen does not provide a clear indication of the feature or action being implemented. It is important to use descriptive branch names that accurately describe the purpose of the branch. For example, instead of a generic name like "feature1," consider using names like "**created\_sidebar**" or "**added\_comments\_section**" that convey the specific feature or action being worked on. :pray: Please rename the branch to a meaningful name. Check out this [official document](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch) for further help. :+1:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 22:49 UTC, shahadat3669 commented on index.html
> +    <main>
Greate Ui! background color should be `#fff`. please consider updating the background color as per the design.👍 
| Your | Design|
| --- | --- |
| ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/55840999/ce8e2eae-2d0b-42d1-8f51-f0897752c4c4) | ![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/55840999/f06c0800-c469-4cc6-81e6-9fe95caf6fd1)   |

2023-06-03 22:49 UTC, shahadat3669 commented on index.html
> +              <button type="button" class="button">See Project</button>
Greate button! it has active stage styles 👍 . But you also need to consider adding hover stage styles. please consider adding hover styles as per in the design. 👍 
![image](https://github.com/Mike47ip/mobilePortfolioWeb/assets/55840999/38feafc2-829d-4e75-9f5d-161c1c82da58)

2023-06-03 22:49 UTC, shahadat3669 commented on index.html
> +          </div>
Well done! 👍 Greate card. But for semantic HTML it is better to use the article tag instant of div. please consider updating it. 🙏 check this [documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article).

2023-06-03 22:49 UTC, shahadat3669 commented on README.md
> +
Please remove the unnecessary text. 🙏 It will be best for visitors.

2023-06-04 00:06 UTC, jmonto55 approved these changes
# STATUS: APPROVED 🟢

Hi @Mike47ip, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![AgreeSealGIF](https://user-images.githubusercontent.com/116701485/232347692-8a213af9-b250-4d2c-a690-7f42d3c630e0.gif)

## Highlights

- [ ] Great UI, it looks just like the Figma design.✅


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-05 08:13 UTC, skyv26 approved these changes
## Hi @Mike47ip, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2Q3ZjZmYjcwZGFmZGJmZGE0OWQzMTQ4MDM4MjhlNTI1NTcwZTI4YSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/xUNd9Yd1YNOiFd2D16/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 
- Correct `GitHub` workflow ✅ 
- Meaningful **Github** commits ✅ 
- Correct `.github/workflows` for linters ✅ 
- Followed *best-practices* ✅ 
- Correct **Semantics** used ✅ 
- Well-structured project ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 21:55 UTC, merged